/* Generated by           cobc 2.0.0 */
/* Generated from         helloworld */
/* Generated at           okt 01 2016 17:28:55 */
/* GnuCOBOL build date    Sep 23 2016 17:57:30 */
/* GnuCOBOL package date  Aug 14 2016 12:21:51 UTC */
/* Compile command        cobc -C helloworld */


/* Module path */
static const char		*cob_module_path = NULL;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {12, (cob_u8_ptr)"Hello, world", &a_1};

