/* Generated by           cobc 2.0.0 */
/* Generated from         helloworld */
/* Generated at           okt 01 2016 17:28:55 */
/* GnuCOBOL build date    Sep 23 2016 17:57:30 */
/* GnuCOBOL package date  Aug 14 2016 12:21:51 UTC */
/* Compile command        cobc -C helloworld */

/* Program local variables for 'hello' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_1;	/* RETURN-CODE */

/* End of data storage */

